"use client";

import { useOrganization, useUser } from "@clerk/nextjs";
import { useQuery } from "convex/react";
import { PackageOpen } from "lucide-react";
import Image from "next/image";
import { useEffect, useState } from "react";

import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Tabs, TabsContent } from "@/components/ui/tabs";
import type {
  FileDoc,
  FileFilterType,
  FilesBrowserProps,
  FileSortDirection,
  FileSortKey,
} from "@/config/types/components.types";
import { api } from "../../../../convex/_generated/api";
import { columns } from "./columns";
import { FileCard, FileCardSkeleton } from "./file-card";
import { DataTable } from "./file-table";
import { SearchBar } from "./search-bar";
import { fileSortDirectionOptions, fileSortOptions, fileTypeOptions, fileTypeOrder } from "@/config/const/components.const";
import { getAllFiles as getShrtlFiles } from "@/app/api/shrtl";
import { getAllFiles as getNotterFiles } from "@/app/api/notter";
import { Checkbox } from "@/components/ui/checkbox";
import { CheckedState } from "@radix-ui/react-checkbox";

export function Placeholder() {
  return (
    <div className="flex flex-col gap-6 w-full items-center my-12 text-zinc-500">
      <PackageOpen className="w-32 h-32"/>
      <div className="text-2xl text-center font-bold">
        Тут ничего нет. 
      </div>
    </div>
  );
}

export function FilesBrowser({ title, shrtl, notter }: FilesBrowserProps) {
  const organization = useOrganization();
  const user = useUser();
  const [query, setQuery] = useState("");
  const [type, setType] = useState<FileFilterType>("all");
  const [sort, setSort] = useState<FileSortKey>("date");
  const [typeSort, setTypeSort] = useState<FileSortDirection>("new");
  const [checked, setChecked] = useState<boolean>(false)
  const [apiFiles, setApiFiles] = useState<FileDoc[] | undefined>(undefined);

  let orgId: string | undefined = undefined;
  if (organization.isLoaded && user.isLoaded) {
    orgId = organization.organization?.id ?? user.user?.id;
  }

  const queryFiles = useQuery(api.files.getFiles, !shrtl && orgId ? {
    orgId,
    type: type === "all" ? undefined : type,
    query
  } : "skip");

  const handleCheckedChange = (checked: CheckedState) => {
    if (typeof checked === "boolean") {
      setChecked(checked);
    }
  };

  useEffect(() => {
    if (orgId) {
      if (shrtl) {
        getShrtlFiles(orgId).then(setApiFiles);
      }

      if (notter) {
        getNotterFiles(orgId).then(setApiFiles);
      }
      
    }
  }, [shrtl, notter, orgId]);

  const files = (shrtl || notter) ? apiFiles : queryFiles;

  const isLoading = files === undefined;

  const modifiedFiles: FileDoc[] =
    files?.map((file) => ({
      ...file,
    })) ?? [];


  // Sorted generated by AI
  // Bradar wat is zis...
  const sortedFiles = (() => {
    let filesToSort = modifiedFiles;

    if (shrtl || notter) {
      if (type !== "all") {
        filesToSort = filesToSort.filter((file) => file.type === type);
      }

      if (query) {
        filesToSort = filesToSort.filter((file) =>
          file.name.toLowerCase().includes(query.toLowerCase())
        );
      }

      if (shrtl && !checked) {
        filesToSort = filesToSort.filter((file) => {
          const expiresInSeconds = "_expiresInSeconds" in file ? (file._expiresInSeconds as number | null | undefined) ?? null : null;
          return expiresInSeconds !== null;
        });
      }
    }

    const sortedByAlphabet = [...filesToSort].sort((a, b) =>
      a.name.localeCompare(b.name)
    );

    const sortedByType = [...filesToSort].sort(
      (a, b) => fileTypeOrder.indexOf(a.type) - fileTypeOrder.indexOf(b.type)
    );

    const sortedByDate = [...filesToSort].sort(
      (a, b) => new Date(b._creationTime).valueOf() - new Date(a._creationTime).valueOf()
    );

    let result = sortedByDate;
    if (sort === "alphabet") {
      result = sortedByAlphabet;
    } else if (sort === "types") {
      result = sortedByType;
    }

    return typeSort === "reverse" ? [...result].reverse() : result;
  })();

  return (
    <div>
      <div className="flex justify-between items-start sm:items-center mb-8 flex-col sm:flex-row gap-4">
        <h1 className="text-3xl font-semibold text-white tracking-tight">{title}</h1>
        <div><SearchBar query={query} setQuery={setQuery} /></div>
      </div>

      <Tabs defaultValue="grid">
        <div className="flex flex-col gap-3 mb-6">
          <div className="flex gap-2 items-start md:items-center flex-col md:flex-row">
            <Label htmlFor="type-select" className="text-white/60 text-sm shrink-0">Показать:</Label>
            <Select value={type} onValueChange={(newType) => setType(newType as FileFilterType)}>
              <SelectTrigger className="w-[160px] border-white/10 bg-white/5 text-white hover:bg-white/10" id="type-select">
                <SelectValue />
              </SelectTrigger>
              <SelectContent className="border-white/10 bg-[#211428] text-white">
                {fileTypeOptions.map((option) => (
                  <SelectItem key={option.value} value={option.value} className="focus:bg-white/10">
                    {option.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>

            <Label htmlFor="sort-select" className="text-white/60 text-sm shrink-0">Сортировать:</Label>
            <Select value={sort} onValueChange={(newSort) => setSort(newSort as FileSortKey)}>
              <SelectTrigger className="w-[160px] border-white/10 bg-white/5 text-white hover:bg-white/10" id="sort-select">
                <SelectValue />
              </SelectTrigger>
              <SelectContent className="border-white/10 bg-[#211428] text-white">
                {fileSortOptions.map((option) => (
                  <SelectItem key={option.value} value={option.value} className="focus:bg-white/10">
                    {option.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>

            <Select value={typeSort} onValueChange={(newSort) => setTypeSort(newSort as FileSortDirection)}>
              <SelectTrigger className="w-[140px] border-white/10 bg-white/5 text-white hover:bg-white/10" id="sort-direction-select">
                <SelectValue />
              </SelectTrigger>
              <SelectContent className="border-white/10 bg-[#211428] text-white">
                {fileSortDirectionOptions.map((option) => (
                  <SelectItem key={option.value} value={option.value} className="focus:bg-white/10">
                    {option.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>

            {shrtl && (
              <div className="flex gap-1 items-center">
                <Label htmlFor="expired-checkbox" className="text-white/60 text-sm shrink-0">Истекшие:</Label>
                <Checkbox
                  id="expired-checkbox"
                  name="expired-checkbox"
                  checked={checked}
                  onCheckedChange={handleCheckedChange}
                />
              </div>
            )}
          </div>
        </div>

        {isLoading && (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mr-2">
            {Array.from({ length: 6 }).map((_, i) => (
              <FileCardSkeleton key={i} />
            ))}
          </div>
        )}

        <TabsContent value="grid">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mr-2">
            {sortedFiles.map((file) => (
              <FileCard key={file._id} file={file} shrtl={shrtl} notter={notter}/>
            ))}
          </div>
        </TabsContent>

        <TabsContent value="table">
          <DataTable columns={columns} data={sortedFiles} />
        </TabsContent>
      </Tabs>

      {!isLoading && sortedFiles.length === 0 && <Placeholder />}
    </div>
  )
}
